version: '3'
services:
    web-crawler:
        container_name: web_crawler
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8080}:80'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            ENVIRONMENT: local
        volumes:
            - '.:/var/www/html'
